package pt.estga.chatbot.context;

public enum ProposalState implements ConversationState {
    AWAITING_PROPOSAL_ACTION,
    WAITING_FOR_PHOTO,
    AWAITING_REUPLOAD_PHOTO,
    AWAITING_LOCATION,
    WAITING_FOR_COORDINATES_HANDLING,
    LOOP_OPTIONS,
    AWAITING_PHOTO_ANALYSIS,
    AWAITING_MARK_SELECTION,
    WAITING_FOR_MARK_CONFIRMATION,
    AWAITING_NEW_MARK_DETAILS,
    AWAITING_MONUMENT_SUGGESTIONS,
    AWAITING_MONUMENT_SELECTION,
    WAITING_FOR_MONUMENT_CONFIRMATION,
    AWAITING_NEW_MONUMENT_NAME,
    SUBMISSION_LOOP_OPTIONS,
    AWAITING_DISCARD_CONFIRMATION,
    AWAITING_NOTES,
    READY_TO_SUBMIT,
    SUBMITTED
}
