package pt.estga.chatbot.context;

public enum ProposalState implements ConversationState {
    PROPOSAL_START,
    WAITING_FOR_PHOTO,
    AWAITING_LOCATION,
    AWAITING_PHOTO_ANALYSIS,
    AWAITING_MARK_SELECTION,
    MARK_SELECTED,
    WAITING_FOR_MARK_CONFIRMATION,
    AWAITING_MONUMENT_SUGGESTIONS,
    WAITING_FOR_MONUMENT_CONFIRMATION,
    AWAITING_NOTES,
    SUBMITTED
}
