package pt.estga.chatbot.context;

public enum ProposalState implements ConversationState {
    AWAITING_PROPOSAL_ACTION,
    WAITING_FOR_PHOTO,
    AWAITING_LOCATION,
    LOOP_OPTIONS,
    AWAITING_PHOTO_ANALYSIS,
    AWAITING_MARK_SELECTION,
    MARK_SELECTED,
    WAITING_FOR_MARK_CONFIRMATION,
    AWAITING_MONUMENT_SUGGESTIONS,
    WAITING_FOR_MONUMENT_CONFIRMATION,
    AWAITING_NEW_MONUMENT_NAME,
    SUBMISSION_LOOP_OPTIONS,
    AWAITING_DISCARD_CONFIRMATION,
    AWAITING_NOTES,
    SUBMITTED
}
