package pt.estga.chatbot.context;

public enum VerificationState implements ConversationState {
    AWAITING_VERIFICATION_METHOD,
    AWAITING_CONTACT,
    AWAITING_VERIFICATION_CODE,
    AWAITING_PHONE_CONNECTION_DECISION,
    PHONE_VERIFICATION_SUCCESS,
    PHONE_CONNECTION_SUCCESS
}
