package pt.estga.proposals.enums;

public enum ProposalStatus {
    IN_PROGRESS,
    AWAITING_MONUMENT_INFO,
    AWAITING_MARK_INFO,
    AWAITING_MARK_SELECTION,
    AWAITING_MONUMENT_SELECTION,
    AWAITING_MONUMENT_VERIFICATION,
    READY_TO_SUBMIT,
    SUBMITTED,
    APPROVED,
    REJECTED
}
