package pt.estga.proposals.enums;

public enum ProposalStatus {
    IN_PROGRESS,
    AWAITING_AUTHENTICATION,
    AWAITING_MONUMENT_INFO,
    AWAITING_MONUMENT_NAME,
    AWAITING_MARK_INFO,
    AWAITING_MARK_SELECTION,
    AWAITING_MONUMENT_SELECTION,
    AWAITING_MONUMENT_VERIFICATION,
    AWAITING_NOTES,
    AWAITING_PHOTO,
    AWAITING_COORDINATES,
    AWAITING_COORDINATES_CONFIRMATION,
    READY_TO_SUBMIT,
    SUBMITTED,
    APPROVED,
    REJECTED,
    PENDING
}
