package pt.estga.chatbots.core.context;

public enum ConversationState {
    START,
    AWAITING_CONTACT,
    AUTHENTICATED,
    WAITING_FOR_PHOTO,
    WAITING_FOR_MARK_CONFIRMATION,
    WAITING_FOR_COORDINATES_HANDLING,
    AWAITING_LOCATION,
    WAITING_FOR_MONUMENT_CONFIRMATION,
    AWAITING_NEW_MONUMENT_NAME,
    AWAITING_MARK_SELECTION,
    AWAITING_NEW_MARK_DETAILS,
    AWAITING_NOTES,
    READY_TO_SUBMIT,
    SUBMITTED,
}
