package pt.estga.auth.enums;

public enum VerificationTokenPurpose {
    EMAIL_VERIFICATION,
    TELEPHONE_VERIFICATION,
    PASSWORD_RESET,
    TWO_FACTOR_AUTHENTICATION,
    EMAIL_CHANGE_REQUEST,
    EMAIL_CHANGE_CONFIRM,
    TELEPHONE_CHANGE_REQUEST,
    TELEPHONE_CHANGE_CONFIRM
}
